#!/bin/bash

EDITIONS='*'
EXTRA=''

while getopts e:x: OPT
do
  case $OPT in
    e) EDITIONS="$OPTARG"
      ;;
    x) EXTRA="$OPTARG"
      ;;
  esac
done

set -f
IFS=, eval 'EDITIONSARR=($EDITIONS)'

pushd `dirname $0`
pushd ..

EDITIONS=(
  YANEURAOU_ENGINE_NNUE
  YANEURAOU_ENGINE_SFNN1536
  YANEURAOU_ENGINE_NNUE_HALFKP_VM_256X2_32_32
  YANEURAOU_ENGINE_NNUE_HALFKPE9
  YANEURAOU_ENGINE_NNUE_KP256
  YANEURAOU_ENGINE_KPPT
  YANEURAOU_ENGINE_KPP_KKPT
  YANEURAOU_ENGINE_MATERIAL
  YANEURAOU_ENGINE_MATERIAL2
  YANEURAOU_ENGINE_MATERIAL3
  YANEURAOU_ENGINE_MATERIAL4
  YANEURAOU_ENGINE_MATERIAL5
  YANEURAOU_ENGINE_MATERIAL6
  YANEURAOU_ENGINE_MATERIAL7
  YANEURAOU_ENGINE_MATERIAL8
  YANEURAOU_ENGINE_MATERIAL9
#  YANEURAOU_ENGINE_MATERIAL10
  YANEURAOU_MATE_ENGINE
  TANUKI_MATE_ENGINE
  USER_ENGINE
)

edition_str() {
  case "$1" in
    YANEURAOU_ENGINE_NNUE) echo "YANEURAOU_ENGINE_NNUE" ;;
    YANEURAOU_ENGINE_SFNN1536) echo "YANEURAOU_ENGINE_SFNN1536" ;;
    YANEURAOU_ENGINE_NNUE_HALFKP_VM_256X2_32_32) echo "YANEURAOU_ENGINE_NNUE_HALFKP_VM_256X2_32_32" ;;
    YANEURAOU_ENGINE_NNUE_HALFKPE9) echo "YANEURAOU_ENGINE_NNUE_HALFKPE9" ;;
    YANEURAOU_ENGINE_NNUE_KP256) echo "YANEURAOU_ENGINE_NNUE_KP256" ;;
    YANEURAOU_ENGINE_KPPT) echo "YANEURAOU_ENGINE_KPPT" ;;
    YANEURAOU_ENGINE_KPP_KKPT) echo "YANEURAOU_ENGINE_KPP_KKPT" ;;
    YANEURAOU_ENGINE_MATERIAL) echo "YANEURAOU_ENGINE_MATERIAL" ;;
    YANEURAOU_ENGINE_MATERIAL2) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=2" ;;
    YANEURAOU_ENGINE_MATERIAL3) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=3" ;;
    YANEURAOU_ENGINE_MATERIAL4) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=4" ;;
    YANEURAOU_ENGINE_MATERIAL5) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=5" ;;
    YANEURAOU_ENGINE_MATERIAL6) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=6" ;;
    YANEURAOU_ENGINE_MATERIAL7) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=7" ;;
    YANEURAOU_ENGINE_MATERIAL8) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=8" ;;
    YANEURAOU_ENGINE_MATERIAL9) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=9" ;;
    YANEURAOU_ENGINE_MATERIAL10) echo "YANEURAOU_ENGINE_MATERIAL MATERIAL_LEVEL=10" ;;
    YANEURAOU_MATE_ENGINE) echo "YANEURAOU_MATE_ENGINE" ;;
    TANUKI_MATE_ENGINE) echo "TANUKI_MATE_ENGINE" ;;
    USER_ENGINE) echo "USER_ENGINE" ;;
    *) return 1 ;;
  esac
}

dir_str() {
  case "$1" in
    YANEURAOU_ENGINE_NNUE) echo "NNUE" ;;
    YANEURAOU_ENGINE_SFNN1536) echo "SFNN1536" ;;
    YANEURAOU_ENGINE_NNUE_HALFKP_VM_256X2_32_32) echo "NNUE_HALFKP_VM" ;;
    YANEURAOU_ENGINE_NNUE_HALFKPE9) echo "NNUE_HALFKPE9" ;;
    YANEURAOU_ENGINE_NNUE_KP256) echo "NNUE_KP256" ;;
    YANEURAOU_ENGINE_KPPT) echo "KPPT" ;;
    YANEURAOU_ENGINE_KPP_KKPT) echo "KPP_KKPT" ;;
    YANEURAOU_ENGINE_MATERIAL) echo "MaterialLv1" ;;
    YANEURAOU_ENGINE_MATERIAL2) echo "MaterialLv2" ;;
    YANEURAOU_ENGINE_MATERIAL3) echo "MaterialLv3" ;;
    YANEURAOU_ENGINE_MATERIAL4) echo "MaterialLv4" ;;
    YANEURAOU_ENGINE_MATERIAL5) echo "MaterialLv5" ;;
    YANEURAOU_ENGINE_MATERIAL6) echo "MaterialLv6" ;;
    YANEURAOU_ENGINE_MATERIAL7) echo "MaterialLv7" ;;
    YANEURAOU_ENGINE_MATERIAL8) echo "MaterialLv8" ;;
    YANEURAOU_ENGINE_MATERIAL9) echo "MaterialLv9" ;;
    YANEURAOU_ENGINE_MATERIAL10) echo "MaterialLv10" ;;
    YANEURAOU_MATE_ENGINE) echo "YaneuraOu_MATE" ;;
    TANUKI_MATE_ENGINE) echo "tanuki_MATE" ;;
    USER_ENGINE) echo "USER" ;;
    *) return 1 ;;
  esac
}

set -f

cpu_count() {
  if command -v nproc >/dev/null 2>&1; then
    nproc
  else
    sysctl -n hw.logicalcpu
  fi
}

for EDITION in ${EDITIONS[@]}; do
  for EDITIONPTN in ${EDITIONSARR[@]}; do
    set +f
    if [[ $EDITION == $EDITIONPTN ]]; then
      set -f
      echo "* edition: ${EDITION}"
      BUILDDIR=build/android/$(dir_str "${EDITION}")
      mkdir -p ${BUILDDIR}
      NDK_ARGS="NDK_PROJECT_PATH=$(pwd) APP_BUILD_SCRIPT=$(pwd)/script/jni/Android.mk NDK_APPLICATION_MK=$(pwd)/script/jni/Application.mk"
      EDITION_ARGS=$(edition_str "${EDITION}") || exit $?
      ndk-build ${NDK_ARGS} clean YANEURAOU_EDITION=${EDITION_ARGS} ${EXTRA}
      ndk-build ${NDK_ARGS} -j$(cpu_count) YANEURAOU_EDITION=${EDITION_ARGS} V=1 ${EXTRA} >& >(tee ${BUILDDIR}/build.log) || exit $?
      bash -c "cp libs/**/* ${BUILDDIR}"
      ndk-build ${NDK_ARGS} clean YANEURAOU_EDITION=${EDITION_ARGS} ${EXTRA}
      break
    fi
    set -f
  done
done

popd
popd
